// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.Accounts.Item.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "registration")]
        #pragma warning disable CS1591
        Registration,
        #pragma warning restore CS1591
    }
}
