// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExternalCashTransfersPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The instruction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction? Instruction { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction Instruction { get; set; }
#endif
        /// <summary>The instructionType property</summary>
        public global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody_instructionType? InstructionType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExternalCashTransfersPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "instruction", n => { Instruction = n.GetObjectValue<global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction>(global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction.CreateFromDiscriminatorValue); } },
                { "instructionType", n => { InstructionType = n.GetEnumValue<global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody_instructionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction>("instruction", Instruction);
            writer.WriteEnumValue<global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody_instructionType>("instructionType", InstructionType);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::IBKR.Api.Kiota.Models.DepositFundsInstruction"/>, <see cref="global::IBKR.Api.Kiota.Models.WithdrawFundsInstruction"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExternalCashTransfersPostRequestBody_instruction : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.DepositFundsInstruction"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.DepositFundsInstruction? DepositFundsInstruction { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.DepositFundsInstruction DepositFundsInstruction { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.WithdrawFundsInstruction"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.WithdrawFundsInstruction? WithdrawFundsInstruction { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.WithdrawFundsInstruction WithdrawFundsInstruction { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::IBKR.Api.Kiota.Gw.Api.V1.ExternalCashTransfers.ExternalCashTransfersPostRequestBody.ExternalCashTransfersPostRequestBody_instruction();
                result.DepositFundsInstruction = new global::IBKR.Api.Kiota.Models.DepositFundsInstruction();
                result.WithdrawFundsInstruction = new global::IBKR.Api.Kiota.Models.WithdrawFundsInstruction();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DepositFundsInstruction != null || WithdrawFundsInstruction != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DepositFundsInstruction, WithdrawFundsInstruction);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.DepositFundsInstruction>(null, DepositFundsInstruction, WithdrawFundsInstruction);
            }
        }
    }
}
#pragma warning restore CS0618
