// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Iserver.Secdef.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSecTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STK")]
        #pragma warning disable CS1591
        STK,
        #pragma warning restore CS1591
        [EnumMember(Value = "IND")]
        #pragma warning disable CS1591
        IND,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOND")]
        #pragma warning disable CS1591
        BOND,
        #pragma warning restore CS1591
    }
}
