// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Client.Portfolio.Positions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Client.Portfolio.Positions
{
    /// <summary>
    /// Builds and executes requests for operations under \portfolio\positions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PositionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IBKR.Api.Kiota.portfolio.positions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder"/></returns>
        public global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("conid", position);
                return new global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the IBKR.Api.Kiota.portfolio.positions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("conid", position);
                return new global::IBKR.Api.Kiota.Client.Portfolio.Positions.Item.WithConItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Portfolio.Positions.PositionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PositionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portfolio/positions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Portfolio.Positions.PositionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PositionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portfolio/positions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
