// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Gw.Api.V1.Instructions.Cancel;
using IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item;
using IBKR.Api.Kiota.Gw.Api.V1.Instructions.Query;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.Instructions
{
    /// <summary>
    /// Builds and executes requests for operations under \gw\api\v1\instructions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstructionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The query property</summary>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Query.QueryRequestBuilder Query
        {
            get => new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the IBKR.Api.Kiota.gw.api.v1.instructions.item collection</summary>
        /// <param name="position">The target instruction id.</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder"/></returns>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("instructionId", position);
                return new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the IBKR.Api.Kiota.gw.api.v1.instructions.item collection</summary>
        /// <param name="position">The target instruction id.</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("instructionId", position);
                return new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.InstructionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstructionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/instructions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.InstructionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstructionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/instructions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
