// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Item;
using IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Rules;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Iserver.Contract
{
    /// <summary>
    /// Builds and executes requests for operations under \iserver\contract
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContractRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rules property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Rules.RulesRequestBuilder Rules
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the IBKR.Api.V2.Generated.Kiota.iserver.contract.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Item.WithConItemRequestBuilder"/></returns>
        public global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Item.WithConItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("conid", position);
                return new global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.Item.WithConItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.ContractRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContractRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/contract", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Iserver.Contract.ContractRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContractRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/contract", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
