// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Client.Gw.Api.V1.BankInstructions.Query
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QueryPostRequestBody_instructionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "QUERY_BANK_INSTRUCTION")]
        #pragma warning disable CS1591
        QUERY_BANK_INSTRUCTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUERY_RECENT_RECURRING_EVENTS")]
        #pragma warning disable CS1591
        QUERY_RECENT_RECURRING_EVENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUERY_RECURRING_INSTRUCTIONS")]
        #pragma warning disable CS1591
        QUERY_RECURRING_INSTRUCTIONS,
        #pragma warning restore CS1591
    }
}
