// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Iserver.Account.Search.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Iserver.Account.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \iserver\account\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IBKR.Api.Kiota.iserver.account.search.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Iserver.Account.Search.Item.WithSearchPatternItemRequestBuilder"/></returns>
        public global::IBKR.Api.Kiota.Iserver.Account.Search.Item.WithSearchPatternItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("searchPattern", position);
                return new global::IBKR.Api.Kiota.Iserver.Account.Search.Item.WithSearchPatternItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Iserver.Account.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/account/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Iserver.Account.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/account/search", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
