// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Client.Gw.Api.V1.Requests.Item.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "response")]
        #pragma warning disable CS1591
        Response,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
    }
}
