// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    /// <summary>Status of the account with respect to clearing at IB. O is open, P pending, N new, A abandoned, C closed, R rejected.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountAttributes_clearingStatus
    {
        [EnumMember(Value = "O")]
        #pragma warning disable CS1591
        O,
        #pragma warning restore CS1591
        [EnumMember(Value = "P")]
        #pragma warning disable CS1591
        P,
        #pragma warning restore CS1591
        [EnumMember(Value = "N")]
        #pragma warning disable CS1591
        N,
        #pragma warning restore CS1591
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "R")]
        #pragma warning disable CS1591
        R,
        #pragma warning restore CS1591
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
    }
}
