// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AssociatedEntity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AssociatedPersons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedPerson>? AssociatedPersons { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedPerson> AssociatedPersons { get; set; }
#endif
        /// <summary>The associations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Associations { get; set; }
#nullable restore
#else
        public List<string> Associations { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The entityId property</summary>
        public int? EntityId { get; set; }
        /// <summary>The externalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCode { get; set; }
#nullable restore
#else
        public string ExternalCode { get; set; }
#endif
        /// <summary>The identityDocuments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_identityDocuments>? IdentityDocuments { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_identityDocuments> IdentityDocuments { get; set; }
#endif
        /// <summary>The mailing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_mailing? Mailing { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_mailing Mailing { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organizationCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationCountry { get; set; }
#nullable restore
#else
        public string OrganizationCountry { get; set; }
#endif
        /// <summary>The phones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_phones? Phones { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_phones Phones { get; set; }
#endif
        /// <summary>The residence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_residence? Residence { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_residence Residence { get; set; }
#endif
        /// <summary>The taxTreatyDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_taxTreatyDetails>? TaxTreatyDetails { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_taxTreatyDetails> TaxTreatyDetails { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity"/> and sets the default values.
        /// </summary>
        public AssociatedEntity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AssociatedPersons", n => { AssociatedPersons = n.GetCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedPerson>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedPerson.CreateFromDiscriminatorValue)?.AsList(); } },
                { "associations", n => { Associations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "entityId", n => { EntityId = n.GetIntValue(); } },
                { "externalCode", n => { ExternalCode = n.GetStringValue(); } },
                { "identityDocuments", n => { IdentityDocuments = n.GetCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_identityDocuments>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_identityDocuments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mailing", n => { Mailing = n.GetObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_mailing>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_mailing.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organizationCountry", n => { OrganizationCountry = n.GetStringValue(); } },
                { "phones", n => { Phones = n.GetObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_phones>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_phones.CreateFromDiscriminatorValue); } },
                { "residence", n => { Residence = n.GetObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_residence>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_residence.CreateFromDiscriminatorValue); } },
                { "taxTreatyDetails", n => { TaxTreatyDetails = n.GetCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_taxTreatyDetails>(global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_taxTreatyDetails.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedPerson>("AssociatedPersons", AssociatedPersons);
            writer.WriteCollectionOfPrimitiveValues<string>("associations", Associations);
            writer.WriteStringValue("email", Email);
            writer.WriteIntValue("entityId", EntityId);
            writer.WriteStringValue("externalCode", ExternalCode);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_identityDocuments>("identityDocuments", IdentityDocuments);
            writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_mailing>("mailing", Mailing);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("organizationCountry", OrganizationCountry);
            writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_phones>("phones", Phones);
            writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_residence>("residence", Residence);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.V2.Generated.Kiota.Models.AssociatedEntity_taxTreatyDetails>("taxTreatyDetails", TaxTreatyDetails);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
