// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContractRules_cqtTypes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "limit")]
        #pragma warning disable CS1591
        Limit,
        #pragma warning restore CS1591
        [EnumMember(Value = "market")]
        #pragma warning disable CS1591
        Market,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop_limit")]
        #pragma warning disable CS1591
        Stop_limit,
        #pragma warning restore CS1591
        [EnumMember(Value = "mit")]
        #pragma warning disable CS1591
        Mit,
        #pragma warning restore CS1591
        [EnumMember(Value = "lit")]
        #pragma warning disable CS1591
        Lit,
        #pragma warning restore CS1591
        [EnumMember(Value = "trailing_stop")]
        #pragma warning disable CS1591
        Trailing_stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "trailing_stop_limit")]
        #pragma warning disable CS1591
        Trailing_stop_limit,
        #pragma warning restore CS1591
    }
}
