// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SuccessfulTickleResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>(Internal Use Only)</summary>
        public bool? Collission { get; set; }
        /// <summary>Returns connection details for the historical market data server.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_hmds? Hmds { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_hmds Hmds { get; set; }
#endif
        /// <summary>The iserver property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_iserver? Iserver { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_iserver Iserver { get; set; }
#endif
        /// <summary>Returns the session token of the contract.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Session { get; set; }
#nullable restore
#else
        public string Session { get; set; }
#endif
        /// <summary>Returns the number of milliseconds until the current sso session expires.</summary>
        public int? SsoExpires { get; set; }
        /// <summary>(Internal Use Only)</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse"/> and sets the default values.
        /// </summary>
        public SuccessfulTickleResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collission", n => { Collission = n.GetBoolValue(); } },
                { "hmds", n => { Hmds = n.GetObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_hmds>(global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_hmds.CreateFromDiscriminatorValue); } },
                { "iserver", n => { Iserver = n.GetObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_iserver>(global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_iserver.CreateFromDiscriminatorValue); } },
                { "session", n => { Session = n.GetStringValue(); } },
                { "ssoExpires", n => { SsoExpires = n.GetIntValue(); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("collission", Collission);
            writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_hmds>("hmds", Hmds);
            writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse_iserver>("iserver", Iserver);
            writer.WriteStringValue("session", Session);
            writer.WriteIntValue("ssoExpires", SsoExpires);
            writer.WriteIntValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
