// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse"/>, <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TickleResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse? FailedTickleResponse { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse FailedTickleResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse? SuccessfulTickleResponse { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse SuccessfulTickleResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TickleResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.V2.Generated.Kiota.Models.TickleResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::IBKR.Api.V2.Generated.Kiota.Models.TickleResponse();
            if("failedTickleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FailedTickleResponse = new global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse();
            }
            else if("successfulTickleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SuccessfulTickleResponse = new global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FailedTickleResponse != null)
            {
                return FailedTickleResponse.GetFieldDeserializers();
            }
            else if(SuccessfulTickleResponse != null)
            {
                return SuccessfulTickleResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(FailedTickleResponse != null)
            {
                writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.FailedTickleResponse>(null, FailedTickleResponse);
            }
            else if(SuccessfulTickleResponse != null)
            {
                writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.SuccessfulTickleResponse>(null, SuccessfulTickleResponse);
            }
        }
    }
}
#pragma warning restore CS0618
