// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1"/>, <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TradingInstrument : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1? TradingInstrumentMember1 { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1 TradingInstrumentMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2? TradingInstrumentMember2 { get; set; }
#nullable restore
#else
        public global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2 TradingInstrumentMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrument"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrument CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrument();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TradingInstrumentMember1 = new global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TradingInstrumentMember2 = new global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TradingInstrumentMember1 != null)
            {
                return TradingInstrumentMember1.GetFieldDeserializers();
            }
            else if(TradingInstrumentMember2 != null)
            {
                return TradingInstrumentMember2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(TradingInstrumentMember1 != null)
            {
                writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember1>(null, TradingInstrumentMember1);
            }
            else if(TradingInstrumentMember2 != null)
            {
                writer.WriteObjectValue<global::IBKR.Api.V2.Generated.Kiota.Models.TradingInstrumentMember2>(null, TradingInstrumentMember2);
            }
        }
    }
}
#pragma warning restore CS0618
