// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Models
{
    /// <summary>The type of entity assigned to the user</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum User_entity_entityType
    {
        [EnumMember(Value = "INDIVIDUAL")]
        #pragma warning disable CS1591
        INDIVIDUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "Joint")]
        #pragma warning disable CS1591
        Joint,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORG")]
        #pragma warning disable CS1591
        ORG,
        #pragma warning restore CS1591
    }
}
