// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Portfolio.Item.Allocation;
using IBKR.Api.Kiota.Portfolio.Item.Ledger;
using IBKR.Api.Kiota.Portfolio.Item.Meta;
using IBKR.Api.Kiota.Portfolio.Item.Position;
using IBKR.Api.Kiota.Portfolio.Item.Positions;
using IBKR.Api.Kiota.Portfolio.Item.Summary;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Portfolio.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \portfolio\{accountId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allocation property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Allocation.AllocationRequestBuilder Allocation
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Allocation.AllocationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ledger property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Ledger.LedgerRequestBuilder Ledger
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Ledger.LedgerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meta property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Meta.MetaRequestBuilder Meta
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Meta.MetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The position property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Position.PositionRequestBuilder Position
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Position.PositionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The positions property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Positions.PositionsRequestBuilder Positions
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Positions.PositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The summary property</summary>
        public global::IBKR.Api.Kiota.Portfolio.Item.Summary.SummaryRequestBuilder Summary
        {
            get => new global::IBKR.Api.Kiota.Portfolio.Item.Summary.SummaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Portfolio.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portfolio/{accountId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Portfolio.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portfolio/{accountId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
