// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Client.Iserver.Auth.Ssodh;
using IBKR.Api.Kiota.Client.Iserver.Auth.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Client.Iserver.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \iserver\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ssodh property</summary>
        public global::IBKR.Api.Kiota.Client.Iserver.Auth.Ssodh.SsodhRequestBuilder Ssodh
        {
            get => new global::IBKR.Api.Kiota.Client.Iserver.Auth.Ssodh.SsodhRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::IBKR.Api.Kiota.Client.Iserver.Auth.Status.StatusRequestBuilder Status
        {
            get => new global::IBKR.Api.Kiota.Client.Iserver.Auth.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Iserver.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Iserver.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
