// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \gw\api\v1\instructions\{instructionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithInstructionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInstructionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/instructions/{instructionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInstructionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/instructions/{instructionId}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve status of request by instructionId&lt;br&gt;&lt;br&gt;**Scope**: `instructions.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IBKR.Api.Kiota.Models.NoSuchInstructionResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.InternalServerErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse?> GetAsWithInstructionGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse> GetAsWithInstructionGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::IBKR.Api.Kiota.Models.NoSuchInstructionResponse.CreateFromDiscriminatorValue },
                { "500", global::IBKR.Api.Kiota.Models.InternalServerErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse>(requestInfo, global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve status of request by instructionId&lt;br&gt;&lt;br&gt;**Scope**: `instructions.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IBKR.Api.Kiota.Models.NoSuchInstructionResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.InternalServerErrorResponse">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithInstructionGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::IBKR.Api.Kiota.Models.NoSuchInstructionResponse.CreateFromDiscriminatorValue },
                { "500", global::IBKR.Api.Kiota.Models.InternalServerErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse>(requestInfo, global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve status of request by instructionId&lt;br&gt;&lt;br&gt;**Scope**: `instructions.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.InstructionPollingResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.InstructionResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithInstructionGetResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse? DepositFundsPollingResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse DepositFundsPollingResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.InstructionPollingResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.InstructionPollingResponse? InstructionPollingResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.InstructionPollingResponse InstructionPollingResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.InstructionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.InstructionResponse? InstructionResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.InstructionResponse InstructionResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse? QueryIRAContributionsResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse QueryIRAContributionsResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse? QueryRecentInstructionResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse QueryRecentInstructionResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionGetResponse();
                result.DepositFundsPollingResponse = new global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse();
                result.InstructionPollingResponse = new global::IBKR.Api.Kiota.Models.InstructionPollingResponse();
                result.InstructionResponse = new global::IBKR.Api.Kiota.Models.InstructionResponse();
                result.QueryIRAContributionsResponse = new global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse();
                result.QueryRecentInstructionResponse = new global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DepositFundsPollingResponse != null || InstructionPollingResponse != null || InstructionResponse != null || QueryIRAContributionsResponse != null || QueryRecentInstructionResponse != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DepositFundsPollingResponse, InstructionPollingResponse, InstructionResponse, QueryIRAContributionsResponse, QueryRecentInstructionResponse);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse>(null, DepositFundsPollingResponse, InstructionPollingResponse, InstructionResponse, QueryIRAContributionsResponse, QueryRecentInstructionResponse);
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithInstructionItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.InstructionPollingResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.InstructionResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse"/>, <see cref="global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithInstructionResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse? DepositFundsPollingResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse DepositFundsPollingResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.InstructionPollingResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.InstructionPollingResponse? InstructionPollingResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.InstructionPollingResponse InstructionPollingResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.InstructionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.InstructionResponse? InstructionResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.InstructionResponse InstructionResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse? QueryIRAContributionsResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse QueryIRAContributionsResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse? QueryRecentInstructionResponse { get; set; }
#nullable restore
#else
            public global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse QueryRecentInstructionResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::IBKR.Api.Kiota.Gw.Api.V1.Instructions.Item.WithInstructionItemRequestBuilder.WithInstructionResponse();
                result.DepositFundsPollingResponse = new global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse();
                result.InstructionPollingResponse = new global::IBKR.Api.Kiota.Models.InstructionPollingResponse();
                result.InstructionResponse = new global::IBKR.Api.Kiota.Models.InstructionResponse();
                result.QueryIRAContributionsResponse = new global::IBKR.Api.Kiota.Models.QueryIRAContributionsResponse();
                result.QueryRecentInstructionResponse = new global::IBKR.Api.Kiota.Models.QueryRecentInstructionResponse();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DepositFundsPollingResponse != null || InstructionPollingResponse != null || InstructionResponse != null || QueryIRAContributionsResponse != null || QueryRecentInstructionResponse != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DepositFundsPollingResponse, InstructionPollingResponse, InstructionResponse, QueryIRAContributionsResponse, QueryRecentInstructionResponse);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.DepositFundsPollingResponse>(null, DepositFundsPollingResponse, InstructionPollingResponse, InstructionResponse, QueryIRAContributionsResponse, QueryRecentInstructionResponse);
            }
        }
    }
}
#pragma warning restore CS0618
