// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Client.Client.Client.Iserver.Secdef.Info
{
    /// <summary>Set the right for the given contract. * `C` - for Call options. * `P` - for Put options.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetRightQueryParameterType
    {
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
        [EnumMember(Value = "P")]
        #pragma warning disable CS1591
        P,
        #pragma warning restore CS1591
    }
}
