// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.V2.Generated.Kiota.Pa.Allperiods;
using IBKR.Api.V2.Generated.Kiota.Pa.Performance;
using IBKR.Api.V2.Generated.Kiota.Pa.Transactions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Pa
{
    /// <summary>
    /// Builds and executes requests for operations under \pa
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allperiods property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Pa.Allperiods.AllperiodsRequestBuilder Allperiods
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Pa.Allperiods.AllperiodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The performance property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Pa.Performance.PerformanceRequestBuilder Performance
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Pa.Performance.PerformanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Pa.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Pa.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Pa.PaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pa", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Pa.PaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pa", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
