// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Params;
using IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Run;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Hmds.Scanner
{
    /// <summary>
    /// Builds and executes requests for operations under \hmds\scanner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScannerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The params property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Params.ParamsRequestBuilder Params
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Params.ParamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Run.RunRequestBuilder Run
        {
            get => new global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.ScannerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScannerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hmds/scanner", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Hmds.Scanner.ScannerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScannerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hmds/scanner", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
