// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Client.V1.Api.Hmds.History
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetBarTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Last")]
        #pragma warning disable CS1591
        Last,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bid")]
        #pragma warning disable CS1591
        Bid,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ask")]
        #pragma warning disable CS1591
        Ask,
        #pragma warning restore CS1591
        [EnumMember(Value = "Midpoint")]
        #pragma warning disable CS1591
        Midpoint,
        #pragma warning restore CS1591
        [EnumMember(Value = "FeeRate")]
        #pragma warning disable CS1591
        FeeRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "Inventory")]
        #pragma warning disable CS1591
        Inventory,
        #pragma warning restore CS1591
    }
}
