using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.V2.Generated.NSwag;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum FormW8IMYFatcaStatus
{
	[EnumMember(Value = "NONPARTICIPATING_FFI")]
	NONPARTICIPATING_FFI,
	[EnumMember(Value = "PARTICIPATING_FFI")]
	PARTICIPATING_FFI,
	[EnumMember(Value = "REPORTING_MODEL1_FFI")]
	REPORTING_MODEL1_FFI,
	[EnumMember(Value = "REPORTING_MODEL2_FFI")]
	REPORTING_MODEL2_FFI,
	[EnumMember(Value = "REGISTERED_DEEMED_COMPLAINT")]
	REGISTERED_DEEMED_COMPLAINT,
	[EnumMember(Value = "TERRITORY_FINANCIAL_INSTITUTION")]
	TERRITORY_FINANCIAL_INSTITUTION,
	[EnumMember(Value = "SPONSORED_FFI")]
	SPONSORED_FFI,
	[EnumMember(Value = "CERTIFIED_DEEMED_COMPLAINT_FFI")]
	CERTIFIED_DEEMED_COMPLAINT_FFI,
	[EnumMember(Value = "CERTIFIED_DEEMED_COMPLAINT_SPONSORED")]
	CERTIFIED_DEEMED_COMPLAINT_SPONSORED,
	[EnumMember(Value = "CERTIFIED_DEEMED_COMPLAINT_LIMITED_LIFE_DEBT")]
	CERTIFIED_DEEMED_COMPLAINT_LIMITED_LIFE_DEBT,
	[EnumMember(Value = "OWNER_DOCUMENTED_FFI")]
	OWNER_DOCUMENTED_FFI,
	[EnumMember(Value = "RESTRICTED_DISTRIBUTOR")]
	RESTRICTED_DISTRIBUTOR,
	[EnumMember(Value = "FOREIGN_CENTRAL_BANK_ISSUE")]
	FOREIGN_CENTRAL_BANK_ISSUE,
	[EnumMember(Value = "NONREPORTING_IGA_FFO")]
	NONREPORTING_IGA_FFO,
	[EnumMember(Value = "EXEMPT_RETIREMENT_PLAN")]
	EXEMPT_RETIREMENT_PLAN,
	[EnumMember(Value = "EXCEPTED_NONFINANCIAL_GROUP_ENTITY")]
	EXCEPTED_NONFINANCIAL_GROUP_ENTITY,
	[EnumMember(Value = "EXCEPTED_NONFINANCIAL_STARTUP_COMPANY")]
	EXCEPTED_NONFINANCIAL_STARTUP_COMPANY,
	[EnumMember(Value = "EXCEPTED_NONFINANCIAL_ENTITY_IN_LIQUIDATION")]
	EXCEPTED_NONFINANCIAL_ENTITY_IN_LIQUIDATION,
	[EnumMember(Value = "PUBLICLY_TRADED_NFFE")]
	PUBLICLY_TRADED_NFFE,
	[EnumMember(Value = "EXCEPTED_TERRITORY_NFFE")]
	EXCEPTED_TERRITORY_NFFE,
	[EnumMember(Value = "ACTIVE_NFFE")]
	ACTIVE_NFFE,
	[EnumMember(Value = "PASSIVE_NFFE")]
	PASSIVE_NFFE,
	[EnumMember(Value = "DIRECT_REPORTING_NFFE")]
	DIRECT_REPORTING_NFFE,
	[EnumMember(Value = "SPONSORED_DIRECT_REPORTING_NFFE")]
	SPONSORED_DIRECT_REPORTING_NFFE
}
