using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.V2.Generated.NSwag;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum FormCRSOecdStatus
{
    [EnumMember(Value = "DEPOSITORY_INSTITUTION")]
    DEPOSITORY_INSTITUTION,

    [EnumMember(Value = "CUSTODIAL_INSTITUTION")]
    CUSTODIAL_INSTITUTION,

    [EnumMember(Value = "SPECIFIED_INSURANCE_COMPANY")]
    SPECIFIED_INSURANCE_COMPANY,

    [EnumMember(Value = "INVESTMENT_ENTITY_IN_NONPARTICIPATING_JURISDICTION")]
    INVESTMENT_ENTITY_IN_NONPARTICIPATING_JURISDICTION,

    [EnumMember(Value = "INVESTMENT_ENTITY_NOT_LISTED")]
    INVESTMENT_ENTITY_NOT_LISTED,

    [EnumMember(Value = "PUBLICLY_TRADED_CORPORATION_OR_AFFILIATE")]
    PUBLICLY_TRADED_CORPORATION_OR_AFFILIATE,

    [EnumMember(Value = "OTHER_ACTIVE_NON_FINANCIAL_ENTITY")]
    OTHER_ACTIVE_NON_FINANCIAL_ENTITY,

    [EnumMember(Value = "PASSIVE_NON_FINANCIAL_ENTITY")]
    PASSIVE_NON_FINANCIAL_ENTITY,

    [EnumMember(Value = "EXEMPT_RETIREMENT_PLAN")]
    EXEMPT_RETIREMENT_PLAN,

    [EnumMember(Value = "NON_REPORTING_FI")]
    NON_REPORTING_FI,

    [EnumMember(Value = "OTHER_INVESTMENT_ENTITY")]
    OTHER_INVESTMENT_ENTITY,

    [EnumMember(Value = "FINANCIAL_INSTITUTION")]
    FINANCIAL_INSTITUTION,

    [EnumMember(Value = "NON_REPORTING_FINANCIAL_INSTITUTION")]
    NON_REPORTING_FINANCIAL_INSTITUTION
}