using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.V2.Generated.NSwag;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum FormW8BENEFatcaStatus
{
    [EnumMember(Value = "NONPARTICIPATING_FFI")]
    NONPARTICIPATING_FFI,

    [EnumMember(Value = "PARICIPATING_FFI")]
    PARICIPATING_FFI,

    [EnumMember(Value = "REPORTING_MODEL_1_FFI")]
    REPORTING_MODEL_1_FFI,

    [EnumMember(Value = "REPORTING_MODEL_2_FFI")]
    REPORTING_MODEL_2_FFI,

    [EnumMember(Value = "REGISTERED_DEEMED_COMPLIANT_FFI")]
    REGISTERED_DEEMED_COMPLIANT_FFI,
    [EnumMember(Value = "SPONSORED_FFI")] SPONSORED_FFI,

    [EnumMember(Value = "CERTIFIED_DEEMED_COMPLIANT_NONREGISTERING_LOCAL_BANK")]
    CERTIFIED_DEEMED_COMPLIANT_NONREGISTERING_LOCAL_BANK,

    [EnumMember(Value = "CERTIFIED_DEEMED_COMPLIANT_FFI")]
    CERTIFIED_DEEMED_COMPLIANT_FFI,

    [EnumMember(Value = "CERTIFIED_DEEMED_COMPLIANT_SPONSORED_VEHICLE")]
    CERTIFIED_DEEMED_COMPLIANT_SPONSORED_VEHICLE,

    [EnumMember(Value = "CERTIFIED_DEEMED_COMPLIANT_LIMITED_LIFE_DEBT")]
    CERTIFIED_DEEMED_COMPLIANT_LIMITED_LIFE_DEBT,

    [EnumMember(Value = "CERTIFIED_DEEMED_COMPLIANT_INVESTMENT_ADVISORS")]
    CERTIFIED_DEEMED_COMPLIANT_INVESTMENT_ADVISORS,

    [EnumMember(Value = "OWNER_DOCUMENTED_FFI")]
    OWNER_DOCUMENTED_FFI,

    [EnumMember(Value = "RESTRICTED_DISTRIBUTOR")]
    RESTRICTED_DISTRIBUTOR,

    [EnumMember(Value = "NONREPORTING_IGA_FFI")]
    NONREPORTING_IGA_FFI,

    [EnumMember(Value = "FOREIGN_GOVERNMENT")]
    FOREIGN_GOVERNMENT,

    [EnumMember(Value = "INTERNATIONAL_ORGANIZATION")]
    INTERNATIONAL_ORGANIZATION,

    [EnumMember(Value = "EXEMPT_RETIREMENT_PLANS")]
    EXEMPT_RETIREMENT_PLANS,

    [EnumMember(Value = "ENTITY_OWNED_BY_EXEMPT_BENEFICIAL_OWNERS")]
    ENTITY_OWNED_BY_EXEMPT_BENEFICIAL_OWNERS,

    [EnumMember(Value = "TERRITORY_FINANCIAL_INSTITUTION")]
    TERRITORY_FINANCIAL_INSTITUTION,

    [EnumMember(Value = "NONFINANCIAL_GROUP")]
    NONFINANCIAL_GROUP,

    [EnumMember(Value = "EXCEPTED_NONFINANCIAL_STARTUP")]
    EXCEPTED_NONFINANCIAL_STARTUP,

    [EnumMember(Value = "EXCEPTED_NONFINANCIAL_ENTITY")]
    EXCEPTED_NONFINANCIAL_ENTITY,

    [EnumMember(Value = "AN_501_C_ORGANIZATION")]
    AN_501_C_ORGANIZATION,

    [EnumMember(Value = "NONPROFIT_ORGANIZATION")]
    NONPROFIT_ORGANIZATION,

    [EnumMember(Value = "PUBLICLY_TRADED_NFFE")]
    PUBLICLY_TRADED_NFFE,

    [EnumMember(Value = "EXCEPTED_TERRITORY_NFFE")]
    EXCEPTED_TERRITORY_NFFE,
    [EnumMember(Value = "ACTIVE_NFFE")] ACTIVE_NFFE,
    [EnumMember(Value = "PASSIVE_NFFE")] PASSIVE_NFFE,

    [EnumMember(Value = "EXCEPTED_INTER_AFFILIATE_FFI")]
    EXCEPTED_INTER_AFFILIATE_FFI,

    [EnumMember(Value = "DIRECT_REPORTING_NFFE")]
    DIRECT_REPORTING_NFFE,

    [EnumMember(Value = "SPONSORED_DIRECT_REPORTING_NFFE")]
    SPONSORED_DIRECT_REPORTING_NFFE
}