// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.InternalCashTransfers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InternalCashTransfersPostRequestBody_instructionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INTERNAL_CASH_TRANSFER")]
        #pragma warning disable CS1591
        INTERNAL_CASH_TRANSFER,
        #pragma warning restore CS1591
    }
}
