// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.Enumerations.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetLanguageQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "en")]
        #pragma warning disable CS1591
        En,
        #pragma warning restore CS1591
        [EnumMember(Value = "ar")]
        #pragma warning disable CS1591
        Ar,
        #pragma warning restore CS1591
        [EnumMember(Value = "de")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "he")]
        #pragma warning disable CS1591
        He,
        #pragma warning restore CS1591
        [EnumMember(Value = "hu")]
        #pragma warning disable CS1591
        Hu,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "ja")]
        #pragma warning disable CS1591
        Ja,
        #pragma warning restore CS1591
        [EnumMember(Value = "nl")]
        #pragma warning disable CS1591
        Nl,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt")]
        #pragma warning disable CS1591
        Pt,
        #pragma warning restore CS1591
        [EnumMember(Value = "ru")]
        #pragma warning disable CS1591
        Ru,
        #pragma warning restore CS1591
        [EnumMember(Value = "zh_CN")]
        #pragma warning disable CS1591
        Zh_CN,
        #pragma warning restore CS1591
        [EnumMember(Value = "zh_TW")]
        #pragma warning disable CS1591
        Zh_TW,
        #pragma warning restore CS1591
    }
}
