// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Algos;
using IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Info;
using IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \iserver\contract\{conid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The algos property</summary>
        public global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Algos.AlgosRequestBuilder Algos
        {
            get => new global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Algos.AlgosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Info.InfoRequestBuilder Info
        {
            get => new global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The infoAndRules property</summary>
        public global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesRequestBuilder InfoAndRules
        {
            get => new global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.WithConItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/contract/{conid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.WithConItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/iserver/contract/{conid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
