// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Pa.Performance
{
    /// <summary>Specify the period for which the account should be analyzed. Available period lengths:  * `1D` - The last 24 hours.  * `7D` - The last 7 full days.  * `MTD` - Performance since the 1st of the month.  * `1M` - A full calendar month from the last full trade day.  * `3M` - 3 full calendar months from the last full trade day.  * `6M` - 6 full calendar months from the last full trade day.  * `12M` - 12 full calendar month from the last full trade day.  * `YTD` - Performance since January 1st.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PerformancePostRequestBody_period
    {
        [EnumMember(Value = "1D")]
        #pragma warning disable CS1591
        OneD,
        #pragma warning restore CS1591
        [EnumMember(Value = "7D")]
        #pragma warning disable CS1591
        SevenD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MTD")]
        #pragma warning disable CS1591
        MTD,
        #pragma warning restore CS1591
        [EnumMember(Value = "1M")]
        #pragma warning disable CS1591
        OneM,
        #pragma warning restore CS1591
        [EnumMember(Value = "3M")]
        #pragma warning disable CS1591
        ThreeM,
        #pragma warning restore CS1591
        [EnumMember(Value = "6M")]
        #pragma warning disable CS1591
        SixM,
        #pragma warning restore CS1591
        [EnumMember(Value = "12M")]
        #pragma warning disable CS1591
        OneTwoM,
        #pragma warning restore CS1591
        [EnumMember(Value = "YTD")]
        #pragma warning disable CS1591
        YTD,
        #pragma warning restore CS1591
    }
}
