using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.NSwag.Contract.Models;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum AutomatedWrapFeeDetailsTypeType
{
	[EnumMember(Value = "ANNUALFLATFEE")]
	ANNUALFLATFEE,
	[EnumMember(Value = "ANNUALFLATFEE_MONTHLY")]
	ANNUALFLATFEE_MONTHLY,
	[EnumMember(Value = "ANNUALFLATFEE_QUATERLY")]
	ANNUALFLATFEE_QUATERLY,
	[EnumMember(Value = "PERCENTOFEQUITY")]
	PERCENTOFEQUITY,
	[EnumMember(Value = "PERCENTOFEQUITY_MONTHLY")]
	PERCENTOFEQUITY_MONTHLY,
	[EnumMember(Value = "PERCENTOFEQUITY_EOM")]
	PERCENTOFEQUITY_EOM,
	[EnumMember(Value = "PERCENTOFEQUITY_QUATERLY")]
	PERCENTOFEQUITY_QUATERLY,
	[EnumMember(Value = "PERCENTOFEQUITY_QUARTERLY")]
	PERCENTOFEQUITY_QUARTERLY,
	[EnumMember(Value = "PERCENTOFEQUITY_EOQ")]
	PERCENTOFEQUITY_EOQ,
	[EnumMember(Value = "BLENDEDPERCENTOFEQUITY")]
	BLENDEDPERCENTOFEQUITY,
	[EnumMember(Value = "BLENDEDPERCENTOFEQUITY_MONTHLY")]
	BLENDEDPERCENTOFEQUITY_MONTHLY,
	[EnumMember(Value = "BLENDEDPERCENTOFEQUITY_EOM")]
	BLENDEDPERCENTOFEQUITY_EOM,
	[EnumMember(Value = "BLENDEDPERCENTOFEQUITY_QUARTERLY")]
	BLENDEDPERCENTOFEQUITY_QUARTERLY,
	[EnumMember(Value = "BLENDEDPERCENTOFEQUITY_EOQ")]
	BLENDEDPERCENTOFEQUITY_EOQ,
	[EnumMember(Value = "INVOICE_LIMIT")]
	INVOICE_LIMIT,
	[EnumMember(Value = "INVOICE_LIMIT_Q")]
	INVOICE_LIMIT_Q,
	[EnumMember(Value = "PERCENTOFPROFIT")]
	PERCENTOFPROFIT,
	[EnumMember(Value = "PERCENTOFPROFIT_QUARTER")]
	PERCENTOFPROFIT_QUARTER,
	[EnumMember(Value = "PERTRADE")]
	PERTRADE,
	[EnumMember(Value = "PERCENTOFNLV_CAP")]
	PERCENTOFNLV_CAP,
	[EnumMember(Value = "PERCENTOFNLV_CAP_EOPEQTY")]
	PERCENTOFNLV_CAP_EOPEQTY,
	[EnumMember(Value = "PERCENTOFNLV_CAP_Q")]
	PERCENTOFNLV_CAP_Q,
	[EnumMember(Value = "PERCENTOFNLV_CAP_EOPEQTY_Q")]
	PERCENTOFNLV_CAP_EOPEQTY_Q
}
