using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.NSwag.Contract.Models;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum PollingInstructionResultInstructionType
{
	[EnumMember(Value = "ACH_INSTRUCTION")]
	ACH_INSTRUCTION,
	[EnumMember(Value = "CANCEL_INSTRUCTION")]
	CANCEL_INSTRUCTION,
	[EnumMember(Value = "COMPLEX_ASSET_TRANSFER")]
	COMPLEX_ASSET_TRANSFER,
	[EnumMember(Value = "DELETE_BANK_INSTRUCTION")]
	DELETE_BANK_INSTRUCTION,
	[EnumMember(Value = "DEPOSIT")]
	DEPOSIT,
	[EnumMember(Value = "DWAC")]
	DWAC,
	[EnumMember(Value = "EXTERNAL_POSITION_TRANSFER")]
	EXTERNAL_POSITION_TRANSFER,
	[EnumMember(Value = "FOP")]
	FOP,
	[EnumMember(Value = "QUERY_RECENT_INSTRUCTIONS")]
	QUERY_RECENT_INSTRUCTIONS,
	[EnumMember(Value = "QUERY_WITHDRAWABLE_FUNDS")]
	QUERY_WITHDRAWABLE_FUNDS,
	[EnumMember(Value = "INTERNAL_POSITION_TRANSFER")]
	INTERNAL_POSITION_TRANSFER,
	[EnumMember(Value = "INTERNAL_CASH_TRANSFER")]
	INTERNAL_CASH_TRANSFER,
	[EnumMember(Value = "MICRO_AMOUNT")]
	MICRO_AMOUNT,
	[EnumMember(Value = "PREDEFINED_DESTINATION_INSTRUCTION")]
	PREDEFINED_DESTINATION_INSTRUCTION,
	[EnumMember(Value = "TRADITIONAL_BANK_INSTRUCTION_VERIFICATION")]
	TRADITIONAL_BANK_INSTRUCTION_VERIFICATION,
	[EnumMember(Value = "WITHDRAWAL")]
	WITHDRAWAL,
	[EnumMember(Value = "QUERY_IRA_CONTRIBUTIONS")]
	QUERY_IRA_CONTRIBUTIONS,
	[EnumMember(Value = "EDDA_INSTRUCTION")]
	EDDA_INSTRUCTION,
	[EnumMember(Value = "QUERY_RECENT_RECURRING_EVENTS")]
	QUERY_RECENT_RECURRING_EVENTS,
	[EnumMember(Value = "QUERY_RECURRING_INSTRUCTIONS")]
	QUERY_RECURRING_INSTRUCTIONS,
	[EnumMember(Value = "QUERY_ACCOUNT_BALANCES")]
	QUERY_ACCOUNT_BALANCES,
	[EnumMember(Value = "QUERY_BANK_INSTRUCTION")]
	QUERY_BANK_INSTRUCTION
}
