// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Client.V1.Api.Trsrv.AllConids;
using IBKR.Api.Kiota.Client.V1.Api.Trsrv.Futures;
using IBKR.Api.Kiota.Client.V1.Api.Trsrv.Secdef;
using IBKR.Api.Kiota.Client.V1.Api.Trsrv.Stocks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IBKR.Api.Kiota.Client.V1.Api.Trsrv
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\api\trsrv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrsrvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allConids property</summary>
        public global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.AllConids.AllConidsRequestBuilder AllConids
        {
            get => new global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.AllConids.AllConidsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The futures property</summary>
        public global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Futures.FuturesRequestBuilder Futures
        {
            get => new global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Futures.FuturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secdef property</summary>
        public global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Secdef.SecdefRequestBuilder Secdef
        {
            get => new global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Secdef.SecdefRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stocks property</summary>
        public global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Stocks.StocksRequestBuilder Stocks
        {
            get => new global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.Stocks.StocksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.TrsrvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrsrvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/trsrv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Client.V1.Api.Trsrv.TrsrvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrsrvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/trsrv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
