// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExternalPositionTransfer_subType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACATS")]
        #pragma warning disable CS1591
        ACATS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATON")]
        #pragma warning disable CS1591
        ATON,
        #pragma warning restore CS1591
    }
}
