// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PollingInstructionResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clientInstructionId property</summary>
        public double? ClientInstructionId { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Models.PollingInstructionResult_error? Error { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Models.PollingInstructionResult_error Error { get; set; }
#endif
        /// <summary>The ibReferenceId property</summary>
        public double? IbReferenceId { get; set; }
        /// <summary>The instructionId property</summary>
        public double? InstructionId { get; set; }
        /// <summary>The instructionStatus property</summary>
        public global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionStatus? InstructionStatus { get; set; }
        /// <summary>The instructionType property</summary>
        public global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionType? InstructionType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Models.PollingInstructionResult"/> and sets the default values.
        /// </summary>
        public PollingInstructionResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.PollingInstructionResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Models.PollingInstructionResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Models.PollingInstructionResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientInstructionId", n => { ClientInstructionId = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_error>(global::IBKR.Api.Kiota.Models.PollingInstructionResult_error.CreateFromDiscriminatorValue); } },
                { "ibReferenceId", n => { IbReferenceId = n.GetDoubleValue(); } },
                { "instructionId", n => { InstructionId = n.GetDoubleValue(); } },
                { "instructionStatus", n => { InstructionStatus = n.GetEnumValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionStatus>(); } },
                { "instructionType", n => { InstructionType = n.GetEnumValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("clientInstructionId", ClientInstructionId);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_error>("error", Error);
            writer.WriteDoubleValue("ibReferenceId", IbReferenceId);
            writer.WriteDoubleValue("instructionId", InstructionId);
            writer.WriteEnumValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionStatus>("instructionStatus", InstructionStatus);
            writer.WriteEnumValue<global::IBKR.Api.Kiota.Models.PollingInstructionResult_instructionType>("instructionType", InstructionType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
