// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Models
{
    /// <summary>
    /// Object containing values of positions sorted by long/short and Sector Group.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PortfolioAllocations_group : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Object containing value of long positions in the account aggregated by Sector Group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_long? Long { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_long Long { get; set; }
#endif
        /// <summary>Object containing value of short positions in the account aggregated by Sector Group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_short? Short { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_short Short { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Models.PortfolioAllocations_group"/> and sets the default values.
        /// </summary>
        public PortfolioAllocations_group()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.PortfolioAllocations_group"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Models.PortfolioAllocations_group CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Models.PortfolioAllocations_group();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "long", n => { Long = n.GetObjectValue<global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_long>(global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_long.CreateFromDiscriminatorValue); } },
                { "short", n => { Short = n.GetObjectValue<global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_short>(global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_short.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_long>("long", Long);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.PortfolioAllocations_group_short>("short", Short);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
