// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryAccountBalancesResult_clientBankAccountWithdrawableBalance : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bankAccountNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountNumber { get; set; }
#nullable restore
#else
        public string BankAccountNumber { get; set; }
#endif
        /// <summary>The bankRoutingNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankRoutingNumber { get; set; }
#nullable restore
#else
        public string BankRoutingNumber { get; set; }
#endif
        /// <summary>The withdrawableBalanceWithoutOriginHold property</summary>
        public double? WithdrawableBalanceWithoutOriginHold { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Models.QueryAccountBalancesResult_clientBankAccountWithdrawableBalance"/> and sets the default values.
        /// </summary>
        public QueryAccountBalancesResult_clientBankAccountWithdrawableBalance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.QueryAccountBalancesResult_clientBankAccountWithdrawableBalance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Models.QueryAccountBalancesResult_clientBankAccountWithdrawableBalance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Models.QueryAccountBalancesResult_clientBankAccountWithdrawableBalance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankAccountNumber", n => { BankAccountNumber = n.GetStringValue(); } },
                { "bankRoutingNumber", n => { BankRoutingNumber = n.GetStringValue(); } },
                { "withdrawableBalanceWithoutOriginHold", n => { WithdrawableBalanceWithoutOriginHold = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bankAccountNumber", BankAccountNumber);
            writer.WriteStringValue("bankRoutingNumber", BankRoutingNumber);
            writer.WriteDoubleValue("withdrawableBalanceWithoutOriginHold", WithdrawableBalanceWithoutOriginHold);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
