// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Returns the currency the account is traded in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Returns the epoch time for the start of requests.</summary>
        public int? From { get; set; }
        /// <summary>Returns the request identifier, getTransactions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Returns if the trades are up to date or not.</summary>
        public bool? IncludesRealTime { get; set; }
        /// <summary>Client portal use only</summary>
        public int? Nd { get; set; }
        /// <summary>Client portal use only</summary>
        public int? Rc { get; set; }
        /// <summary>Returns the object containing the realized pnl for the contract on the date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Models.TransactionsResponse_rpnl? Rpnl { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Models.TransactionsResponse_rpnl Rpnl { get; set; }
#endif
        /// <summary>Returns the epoch time for the end of requests.</summary>
        public int? To { get; set; }
        /// <summary>Lists all supported transaction values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Models.TransactionsResponse_transactions>? Transactions { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Models.TransactionsResponse_transactions> Transactions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Models.TransactionsResponse"/> and sets the default values.
        /// </summary>
        public TransactionsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.TransactionsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Models.TransactionsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Models.TransactionsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "from", n => { From = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "includesRealTime", n => { IncludesRealTime = n.GetBoolValue(); } },
                { "nd", n => { Nd = n.GetIntValue(); } },
                { "rc", n => { Rc = n.GetIntValue(); } },
                { "rpnl", n => { Rpnl = n.GetObjectValue<global::IBKR.Api.Kiota.Models.TransactionsResponse_rpnl>(global::IBKR.Api.Kiota.Models.TransactionsResponse_rpnl.CreateFromDiscriminatorValue); } },
                { "to", n => { To = n.GetIntValue(); } },
                { "transactions", n => { Transactions = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Models.TransactionsResponse_transactions>(global::IBKR.Api.Kiota.Models.TransactionsResponse_transactions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteIntValue("from", From);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("includesRealTime", IncludesRealTime);
            writer.WriteIntValue("nd", Nd);
            writer.WriteIntValue("rc", Rc);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Models.TransactionsResponse_rpnl>("rpnl", Rpnl);
            writer.WriteIntValue("to", To);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Models.TransactionsResponse_transactions>("transactions", Transactions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
