// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Gw.Api.V1.Requests.Item;
using IBKR.Api.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IBKR.Api.Kiota.Gw.Api.V1.Requests
{
    /// <summary>
    /// Builds and executes requests for operations under \gw\api\v1\requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IBKR.Api.Kiota.gw.api.v1.requests.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder"/></returns>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("requestId", position);
                return new global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the IBKR.Api.Kiota.gw.api.v1.requests.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("requestId", position);
                return new global::IBKR.Api.Kiota.Gw.Api.V1.Requests.Item.WithRequestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/requests?requestDetails={requestDetails}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/requests?requestDetails={requestDetails}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch Requests&apos; Details By Timeframe&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.RequestDetailsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ProblemDetailResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ProblemDetailResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ProblemDetailResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ProblemDetailResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IBKR.Api.Kiota.Models.RequestDetailsResponse?> GetAsync(Action<RequestConfiguration<global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder.RequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IBKR.Api.Kiota.Models.RequestDetailsResponse> GetAsync(Action<RequestConfiguration<global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder.RequestsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IBKR.Api.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "401", global::IBKR.Api.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "403", global::IBKR.Api.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "500", global::IBKR.Api.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IBKR.Api.Kiota.Models.RequestDetailsResponse>(requestInfo, global::IBKR.Api.Kiota.Models.RequestDetailsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch Requests&apos; Details By Timeframe&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder.RequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder.RequestsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch Requests&apos; Details By Timeframe&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RequestsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("requestDetails")]
            public string? RequestDetails { get; set; }
#nullable restore
#else
            [QueryParameter("requestDetails")]
            public string RequestDetails { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RequestsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IBKR.Api.Kiota.Gw.Api.V1.Requests.RequestsRequestBuilder.RequestsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
