// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Contract.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfoAndRulesGetResponse : global::IBKR.Api.Kiota.Contract.Models.ContractInfo, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>detailed contract information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.ContractRules? Rules { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.ContractRules Rules { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "rules", n => { Rules = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.ContractRules>(global::IBKR.Api.Kiota.Contract.Models.ContractRules.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.ContractRules>("rules", Rules);
        }
    }
}
#pragma warning restore CS0618
