// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Client.Client.Client.Client.Iserver.Contract.Item.InfoAndRules
{
    [Obsolete("This class is obsolete. Use InfoAndRulesGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfoAndRulesResponse : global::IBKR.Api.Kiota.Client.Client.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Client.Client.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::IBKR.Api.Kiota.Client.Client.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Client.Client.Client.Client.Iserver.Contract.Item.InfoAndRules.InfoAndRulesResponse();
        }
    }
}
#pragma warning restore CS0618
