// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.V2.Generated.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms
{
    /// <summary>
    /// Builds and executes requests for operations under \gw\api\v1\forms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FormsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FormsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/forms{?formNo,fromDate,getDocs,language,projection,toDate}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FormsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gw/api/v1/forms{?formNo,fromDate,getDocs,language,projection,toDate}", rawUrl)
        {
        }
        /// <summary>
        /// Get forms&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read` OR `forms.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Models.FormFileResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IBKR.Api.V2.Generated.Kiota.Models.FormFileResponse?> GetAsync(Action<RequestConfiguration<global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder.FormsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IBKR.Api.V2.Generated.Kiota.Models.FormFileResponse> GetAsync(Action<RequestConfiguration<global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder.FormsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "401", global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "403", global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
                { "500", global::IBKR.Api.V2.Generated.Kiota.Models.ProblemDetailResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IBKR.Api.V2.Generated.Kiota.Models.FormFileResponse>(requestInfo, global::IBKR.Api.V2.Generated.Kiota.Models.FormFileResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get forms&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read` OR `forms.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder.FormsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder.FormsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get forms&lt;br&gt;&lt;br&gt;**Scope**: `accounts.read` OR `forms.read`&lt;br&gt;**Security Policy**: `HTTPS`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FormsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("formNo")]
            public int?[]? FormNo { get; set; }
#nullable restore
#else
            [QueryParameter("formNo")]
            public int?[] FormNo { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fromDate")]
            public string? FromDate { get; set; }
#nullable restore
#else
            [QueryParameter("fromDate")]
            public string FromDate { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("getDocs")]
            public string? GetDocs { get; set; }
#nullable restore
#else
            [QueryParameter("getDocs")]
            public string GetDocs { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
            [Obsolete("This property is deprecated, use ProjectionAsGetProjectionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("projection")]
            public string? Projection { get; set; }
#nullable restore
#else
            [QueryParameter("projection")]
            public string Projection { get; set; }
#endif
            [QueryParameter("projection")]
            public global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.GetProjectionQueryParameterType? ProjectionAsGetProjectionQueryParameterType { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("toDate")]
            public string? ToDate { get; set; }
#nullable restore
#else
            [QueryParameter("toDate")]
            public string ToDate { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FormsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IBKR.Api.V2.Generated.Kiota.Gw.Api.V1.Forms.FormsRequestBuilder.FormsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
