using System.CodeDom.Compiler;
using System.Runtime.Serialization;

namespace IBKR.Api.V2.Generated.NSwag.Models;

[GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum FormW8IMYEntityType
{
	[EnumMember(Value = "QUALIFIED_INTERMEDIARY")]
	QUALIFIED_INTERMEDIARY,
	[EnumMember(Value = "NONQUALIFIED_INTERMEDIARY")]
	NONQUALIFIED_INTERMEDIARY,
	[EnumMember(Value = "TERRITORY_FINANCIAL")]
	TERRITORY_FINANCIAL,
	[EnumMember(Value = "US_BRANCH")]
	US_BRANCH,
	[EnumMember(Value = "WITHHOLDING_FOREIGN_PARTNERSHIP")]
	WITHHOLDING_FOREIGN_PARTNERSHIP,
	[EnumMember(Value = "WITHHOLDING_FOREIGN_TRUST")]
	WITHHOLDING_FOREIGN_TRUST,
	[EnumMember(Value = "NONWITHHOLDING_FOREIGN_PARTNERSHIP")]
	NONWITHHOLDING_FOREIGN_PARTNERSHIP,
	[EnumMember(Value = "NONWITHHOLDING_FOREIGN_SIMPLE_TRUST")]
	NONWITHHOLDING_FOREIGN_SIMPLE_TRUST,
	[EnumMember(Value = "NONWITHHOLDING_FOREIGN_GRANTOR_TRUST")]
	NONWITHHOLDING_FOREIGN_GRANTOR_TRUST
}
