// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Contract.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountDetailsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.AccountData? Account { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.AccountData Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The associatedEntities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.AssociatedEntity>? AssociatedEntities { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.AssociatedEntity> AssociatedEntities { get; set; }
#endif
        /// <summary>The associatedPersons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.AssociatedPerson>? AssociatedPersons { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.AssociatedPerson> AssociatedPersons { get; set; }
#endif
        /// <summary>The decedents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_decedents>? Decedents { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_decedents> Decedents { get; set; }
#endif
        /// <summary>The entityIRABeneficiaries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.EntityIRABene>? EntityIRABeneficiaries { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.EntityIRABene> EntityIRABeneficiaries { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.ErrorResponse? Error { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.ErrorResponse Error { get; set; }
#endif
        /// <summary>The errorDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorDescription { get; set; }
#nullable restore
#else
        public string ErrorDescription { get; set; }
#endif
        /// <summary>The financialInformation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_financialInformation? FinancialInformation { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_financialInformation FinancialInformation { get; set; }
#endif
        /// <summary>The hasError property</summary>
        public bool? HasError { get; set; }
        /// <summary>The individualIRABeneficiaries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.IndividualIRABene>? IndividualIRABeneficiaries { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.IndividualIRABene> IndividualIRABeneficiaries { get; set; }
#endif
        /// <summary>The marketData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_marketData>? MarketData { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_marketData> MarketData { get; set; }
#endif
        /// <summary>The restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.RestrictionInfo>? Restrictions { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.RestrictionInfo> Restrictions { get; set; }
#endif
        /// <summary>The sourcesOfWealth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_sourcesOfWealth>? SourcesOfWealth { get; set; }
#nullable restore
#else
        public List<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_sourcesOfWealth> SourcesOfWealth { get; set; }
#endif
        /// <summary>The tradeBundles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TradeBundles { get; set; }
#nullable restore
#else
        public List<string> TradeBundles { get; set; }
#endif
        /// <summary>The withHoldingStatement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_withHoldingStatement? WithHoldingStatement { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_withHoldingStatement WithHoldingStatement { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse"/> and sets the default values.
        /// </summary>
        public AccountDetailsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountData>(global::IBKR.Api.Kiota.Contract.Models.AccountData.CreateFromDiscriminatorValue); } },
                { "associatedEntities", n => { AssociatedEntities = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AssociatedEntity>(global::IBKR.Api.Kiota.Contract.Models.AssociatedEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "associatedPersons", n => { AssociatedPersons = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AssociatedPerson>(global::IBKR.Api.Kiota.Contract.Models.AssociatedPerson.CreateFromDiscriminatorValue)?.AsList(); } },
                { "decedents", n => { Decedents = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_decedents>(global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_decedents.CreateFromDiscriminatorValue)?.AsList(); } },
                { "entityIRABeneficiaries", n => { EntityIRABeneficiaries = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.EntityIRABene>(global::IBKR.Api.Kiota.Contract.Models.EntityIRABene.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error", n => { Error = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.ErrorResponse>(global::IBKR.Api.Kiota.Contract.Models.ErrorResponse.CreateFromDiscriminatorValue); } },
                { "errorDescription", n => { ErrorDescription = n.GetStringValue(); } },
                { "financialInformation", n => { FinancialInformation = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_financialInformation>(global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_financialInformation.CreateFromDiscriminatorValue); } },
                { "hasError", n => { HasError = n.GetBoolValue(); } },
                { "individualIRABeneficiaries", n => { IndividualIRABeneficiaries = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.IndividualIRABene>(global::IBKR.Api.Kiota.Contract.Models.IndividualIRABene.CreateFromDiscriminatorValue)?.AsList(); } },
                { "marketData", n => { MarketData = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_marketData>(global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_marketData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "restrictions", n => { Restrictions = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.RestrictionInfo>(global::IBKR.Api.Kiota.Contract.Models.RestrictionInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sourcesOfWealth", n => { SourcesOfWealth = n.GetCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_sourcesOfWealth>(global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_sourcesOfWealth.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tradeBundles", n => { TradeBundles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "withHoldingStatement", n => { WithHoldingStatement = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_withHoldingStatement>(global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_withHoldingStatement.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountData>("account", Account);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AssociatedEntity>("associatedEntities", AssociatedEntities);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AssociatedPerson>("associatedPersons", AssociatedPersons);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_decedents>("decedents", Decedents);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.EntityIRABene>("entityIRABeneficiaries", EntityIRABeneficiaries);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.ErrorResponse>("error", Error);
            writer.WriteStringValue("errorDescription", ErrorDescription);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_financialInformation>("financialInformation", FinancialInformation);
            writer.WriteBoolValue("hasError", HasError);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.IndividualIRABene>("individualIRABeneficiaries", IndividualIRABeneficiaries);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_marketData>("marketData", MarketData);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.RestrictionInfo>("restrictions", Restrictions);
            writer.WriteCollectionOfObjectValues<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_sourcesOfWealth>("sourcesOfWealth", SourcesOfWealth);
            writer.WriteCollectionOfPrimitiveValues<string>("tradeBundles", TradeBundles);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.AccountDetailsResponse_withHoldingStatement>("withHoldingStatement", WithHoldingStatement);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
