// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IBKR.Api.Kiota.Contract.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AvailableStatementDatesData_value : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>annual available reports</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Annual { get; set; }
#nullable restore
#else
        public List<string> Annual { get; set; }
#endif
        /// <summary>The daily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value_daily? Daily { get; set; }
#nullable restore
#else
        public global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value_daily Daily { get; set; }
#endif
        /// <summary>monthly available reports</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Monthly { get; set; }
#nullable restore
#else
        public List<string> Monthly { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value"/> and sets the default values.
        /// </summary>
        public AvailableStatementDatesData_value()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annual", n => { Annual = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "daily", n => { Daily = n.GetObjectValue<global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value_daily>(global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value_daily.CreateFromDiscriminatorValue); } },
                { "monthly", n => { Monthly = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("annual", Annual);
            writer.WriteObjectValue<global::IBKR.Api.Kiota.Contract.Models.AvailableStatementDatesData_value_daily>("daily", Daily);
            writer.WriteCollectionOfPrimitiveValues<string>("monthly", Monthly);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
