// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Contract.Models
{
    /// <summary>Status of the order ticket.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LiveOrdersResponse_orders_status
    {
        [EnumMember(Value = "Inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "PendingSubmit")]
        #pragma warning disable CS1591
        PendingSubmit,
        #pragma warning restore CS1591
        [EnumMember(Value = "PreSubmitted")]
        #pragma warning disable CS1591
        PreSubmitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "Submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "Filled")]
        #pragma warning disable CS1591
        Filled,
        #pragma warning restore CS1591
        [EnumMember(Value = "PendingCancel")]
        #pragma warning disable CS1591
        PendingCancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "WarnState")]
        #pragma warning disable CS1591
        WarnState,
        #pragma warning restore CS1591
    }
}
