// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IBKR.Api.Kiota.Contract.Models
{
    /// <summary>Side of the order ticket.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderStatus_side
    {
        [EnumMember(Value = "BUY")]
        #pragma warning disable CS1591
        BUY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELL")]
        #pragma warning disable CS1591
        SELL,
        #pragma warning restore CS1591
    }
}
