// <auto-generated/>
#pragma warning disable CS0618
using IBKR.Api.Kiota.Fyi.Deliveryoptions.Device;
using IBKR.Api.Kiota.Fyi.Deliveryoptions.Email;
using IBKR.Api.Kiota.Fyi.Deliveryoptions.Item;
using IBKR.Api.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IBKR.Api.Kiota.Fyi.Deliveryoptions
{
    /// <summary>
    /// Builds and executes requests for operations under \fyi\deliveryoptions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliveryoptionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The device property</summary>
        public global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Device.DeviceRequestBuilder Device
        {
            get => new global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Device.DeviceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Email.EmailRequestBuilder Email
        {
            get => new global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the IBKR.Api.Kiota.fyi.deliveryoptions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Item.WithDeviceItemRequestBuilder"/></returns>
        public global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Item.WithDeviceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deviceId", position);
                return new global::IBKR.Api.Kiota.Fyi.Deliveryoptions.Item.WithDeviceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Fyi.Deliveryoptions.DeliveryoptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryoptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fyi/deliveryoptions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IBKR.Api.Kiota.Fyi.Deliveryoptions.DeliveryoptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryoptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fyi/deliveryoptions", rawUrl)
        {
        }
        /// <summary>
        /// Options for sending fyis to email and other devices.
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Models.DeliveryOptions"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ErrorOnlyResponse">When receiving a 500 status code</exception>
        /// <exception cref="global::IBKR.Api.Kiota.Models.ErrorResponse">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IBKR.Api.Kiota.Models.DeliveryOptions?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IBKR.Api.Kiota.Models.DeliveryOptions> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::IBKR.Api.Kiota.Models.ErrorOnlyResponse.CreateFromDiscriminatorValue },
                { "503", global::IBKR.Api.Kiota.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IBKR.Api.Kiota.Models.DeliveryOptions>(requestInfo, global::IBKR.Api.Kiota.Models.DeliveryOptions.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Options for sending fyis to email and other devices.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IBKR.Api.Kiota.Fyi.Deliveryoptions.DeliveryoptionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IBKR.Api.Kiota.Fyi.Deliveryoptions.DeliveryoptionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IBKR.Api.Kiota.Fyi.Deliveryoptions.DeliveryoptionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeliveryoptionsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
